Lab 24 Numpy

Intrduction to NumPy
1. Import NumPy under the name np.

In [1]:
print(5)

5


In [2]:
import numpy as np

2. Print your NumPy version.

In [3]:
print(np.__version__)

1.21.5


3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable a.

4. Print a.

In [15]:
a = np.random.random((2, 3, 5))
a

array([[[0.21173541, 0.91276754, 0.89231243, 0.18356038, 0.32090756],
        [0.66478175, 0.26007279, 0.99116583, 0.74621805, 0.38482048],
        [0.59797575, 0.82063408, 0.9880698 , 0.87277494, 0.78276818]],

       [[0.50729173, 0.65366149, 0.05781761, 0.36482339, 0.09283169],
        [0.03768137, 0.56717504, 0.96764738, 0.11024709, 0.64656289],
        [0.09751665, 0.8437646 , 0.98192091, 0.93329245, 0.50751633]]])

In [16]:
a2 = np.random.default_rng(1)
type(a2)

numpy.random._generator.Generator

5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable b.

6. Print b.

In [26]:
b = np.zeros((5, 3, 2), dtype=int) + 1
b

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]])

7. Do a and b have the same size? How do you prove that in Python code?

In [27]:
a.shape == b.shape

False

8. Are you able to add a and b? Why or why not?
No. We cannot add matrices of different sizes.

9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to variable c.

In [28]:
c = b.transpose()
c.shape

(2, 3, 5)

10. Try to add a and c. Now it should work. Assign the sum to variable d. But why does it work now?

In [29]:
d = a + c
d

array([[[1.21173541, 1.91276754, 1.89231243, 1.18356038, 1.32090756],
        [1.66478175, 1.26007279, 1.99116583, 1.74621805, 1.38482048],
        [1.59797575, 1.82063408, 1.9880698 , 1.87277494, 1.78276818]],

       [[1.50729173, 1.65366149, 1.05781761, 1.36482339, 1.09283169],
        [1.03768137, 1.56717504, 1.96764738, 1.11024709, 1.64656289],
        [1.09751665, 1.8437646 , 1.98192091, 1.93329245, 1.50751633]]])

11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

In [30]:
print(a)
print(d)

[[[0.21173541 0.91276754 0.89231243 0.18356038 0.32090756]
  [0.66478175 0.26007279 0.99116583 0.74621805 0.38482048]
  [0.59797575 0.82063408 0.9880698  0.87277494 0.78276818]]

 [[0.50729173 0.65366149 0.05781761 0.36482339 0.09283169]
  [0.03768137 0.56717504 0.96764738 0.11024709 0.64656289]
  [0.09751665 0.8437646  0.98192091 0.93329245 0.50751633]]]
[[[1.21173541 1.91276754 1.89231243 1.18356038 1.32090756]
  [1.66478175 1.26007279 1.99116583 1.74621805 1.38482048]
  [1.59797575 1.82063408 1.9880698  1.87277494 1.78276818]]

 [[1.50729173 1.65366149 1.05781761 1.36482339 1.09283169]
  [1.03768137 1.56717504 1.96764738 1.11024709 1.64656289]
  [1.09751665 1.8437646  1.98192091 1.93329245 1.50751633]]]


d has the elements from a plus 1.

12. Multiply a and c. Assign the result to e.

13. Does e equal to a? Why or why not?

In [33]:
e = np.multiply(a, c)
a == e


array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

14. Identify the max, min, and mean values in d. Assign those values to variables d_max, d_min and d_mean.

In [36]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

15. Now we want to label the values in d. First create an empty array f with the same shape (i.e. 2x3x5) as d using np.empty.

In [37]:
f = np.empty((2, 3, 5))
f

array([[[0.21173541, 0.91276754, 0.89231243, 0.18356038, 0.32090756],
        [0.66478175, 0.26007279, 0.99116583, 0.74621805, 0.38482048],
        [0.59797575, 0.82063408, 0.9880698 , 0.87277494, 0.78276818]],

       [[0.50729173, 0.65366149, 0.05781761, 0.36482339, 0.09283169],
        [0.03768137, 0.56717504, 0.96764738, 0.11024709, 0.64656289],
        [0.09751665, 0.8437646 , 0.98192091, 0.93329245, 0.50751633]]])

16. Populate the values in f.
For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f. If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f. If a value equals to d_mean, assign 50 to the corresponding value in f. Assign 0 to the corresponding value(s) in f for d_min in d. Assign 100 to the corresponding value(s) in f for d_max in d. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

In [38]:
for i in range(2) :
    for j in range(3) :
        for k in range(5) :
            d_ijk = d[i, j, k]
            if d_ijk == d_min :
                f[i, j, k] = 0
            elif d_ijk < d_mean :
                f[i, j, k] = 25
            elif d_ijk == d_mean :
                f[i, j, k] = 50
            elif d_ijk < d_max :
                f[i, j, k] = 75
            else :
                f[i, j, k] = 100
f

array([[[ 25.,  75.,  75.,  25.,  25.],
        [ 75.,  25., 100.,  75.,  25.],
        [ 75.,  75.,  75.,  75.,  75.]],

       [[ 25.,  75.,  25.,  25.,  25.],
        [  0.,  75.,  75.,  25.,  75.],
        [ 25.,  75.,  75.,  75.,  25.]]])

17. Print d and f. Do you have your expected f?

In [39]:
print(d)
print(f)

[[[1.21173541 1.91276754 1.89231243 1.18356038 1.32090756]
  [1.66478175 1.26007279 1.99116583 1.74621805 1.38482048]
  [1.59797575 1.82063408 1.9880698  1.87277494 1.78276818]]

 [[1.50729173 1.65366149 1.05781761 1.36482339 1.09283169]
  [1.03768137 1.56717504 1.96764738 1.11024709 1.64656289]
  [1.09751665 1.8437646  1.98192091 1.93329245 1.50751633]]]
[[[ 25.  75.  75.  25.  25.]
  [ 75.  25. 100.  75.  25.]
  [ 75.  75.  75.  75.  75.]]

 [[ 25.  75.  25.  25.  25.]
  [  0.  75.  75.  25.  75.]
  [ 25.  75.  75.  75.  25.]]]


18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

In [40]:
g = np.empty((2, 3, 5), dtype = str)

In [41]:
for i in range(2) :
    for j in range(3) :
        for k in range(5) :
            d_ijk = d[i, j, k]
            if d_ijk == d_min :
                g[i, j, k] = 'A'
            elif d_ijk < d_mean :
                g[i, j, k] = 'B'
            elif d_ijk == d_mean :
                g[i, j, k] = 'C'
            elif d_ijk < d_max :
                g[i, j, k] = 'D'
            else :
                g[i, j, k] = 'F'

In [42]:
g

array([[['B', 'D', 'D', 'B', 'B'],
        ['D', 'B', 'F', 'D', 'B'],
        ['D', 'D', 'D', 'D', 'D']],

       [['B', 'D', 'B', 'B', 'B'],
        ['A', 'D', 'D', 'B', 'D'],
        ['B', 'D', 'D', 'D', 'B']]], dtype='<U1')