In [1]:
import numpy as np


In [2]:
l=[2, 3, 1]
l

[2, 3, 1]

In [3]:
a = np.array(l)
a


array([2, 3, 1])

In [4]:
a.dtype 

dtype('int32')

In [5]:
b = np.array([1.2, 3.5, 5.1])
b.dtype

dtype('float64')

In [5]:
b = np.array([(1.5, 2, 3), (4, 5, 6)])
b


array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [7]:
c=np.array([(1.9999, 2. , 3. ),
       (4. , 5. , 6. )], dtype=int)
c

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
d=np.zeros((6, 4, 4), dtype=int)
d

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [10]:
e=np.arange(10,50,10)
e

array([10, 20, 30, 40])

In [11]:
f=e-5
f

array([ 5, 15, 25, 35])

In [12]:
f1=f*2
f1

array([10, 30, 50, 70])

In [13]:
A = np.array([[1, 2],[3, 4]])
A


array([[1, 2],
       [3, 4]])

In [14]:
B = np.array([[5, 6], [7, 8]])
B

array([[5, 6],
       [7, 8]])

In [44]:
A@B

array([[19, 22],
       [43, 50]])

In [24]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [31]:
rg = np.random.default_rng(1)
b = rg.random((2, 3))
b

array([[0.51182162, 0.9504637 , 0.14415961],
       [0.94864945, 0.31183145, 0.42332645]])

In [22]:
b = np.arange(12).reshape(3, 4)
b


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [27]:
x=np.random.random(2)
x

array([0.2907885 , 0.60686714])

In [22]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [49]:
b.sum(axis=1)     



array([ 6, 22, 38])

In [30]:
b.min(axis=0 )    # min of each row


array([0, 1, 2, 3])

In [23]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [26]:
b.sum(axis=1)

array([ 6, 22, 38])

In [29]:
b.cumsum(axis=1)  # cumulative sum along each row


array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

In [34]:
h = np.arange(12).reshape(3, 4)

h

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [35]:
h.cumsum(axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21]], dtype=int32)

In [38]:
new_h.shape

(6, 2)

In [30]:
a=np.random.random((2,2))
b=np.random.random((4,3,2))
c=np.random.random((5,4,3,2))


In [33]:
a=np.random.random((2,2))
a

array([[0.46897156, 0.7566238 ],
       [0.93702964, 0.80414169]])

In [34]:
a[0,0]

0.4689715591661504

In [35]:
b=np.random.random((4,3,2))
b

array([[[0.78420188, 0.47861149],
        [0.32028097, 0.11134269],
        [0.21165848, 0.89334079]],

       [[0.68887712, 0.12647609],
        [0.54501149, 0.5502087 ],
        [0.74925989, 0.55069201]],

       [[0.571283  , 0.92218203],
        [0.4529212 , 0.60129134],
        [0.44133877, 0.06695105]],

       [[0.42433161, 0.36043611],
        [0.75289922, 0.01893171],
        [0.81237453, 0.59169335]]])

In [36]:
b[0,0,0]

0.7842018824603215

In [31]:
print(c)



[[[[0.58080427 0.33777267]
   [0.35340161 0.80191631]
   [0.38146835 0.70258586]]

  [[0.05641568 0.02830785]
   [0.62131551 0.31040094]
   [0.62148698 0.78821259]]

  [[0.42474815 0.25546292]
   [0.03120571 0.18565137]
   [0.26596561 0.06790796]]

  [[0.86917416 0.45834514]
   [0.18196926 0.9377256 ]
   [0.28161765 0.71949401]]]


 [[[0.60157194 0.44509589]
   [0.81171581 0.895986  ]
   [0.08605846 0.36634218]]

  [[0.45323512 0.36232325]
   [0.74678035 0.93219117]
   [0.52070908 0.61810723]]

  [[0.4315088  0.73691522]
   [0.38281283 0.20431051]
   [0.56534745 0.83621412]]

  [[0.75256289 0.61653348]
   [0.50909782 0.06907103]
   [0.0223834  0.19136134]]]


 [[[0.62586748 0.88595009]
   [0.85775555 0.99474266]
   [0.78081682 0.83125809]]

  [[0.64861893 0.54861401]
   [0.14421662 0.0601093 ]
   [0.4263398  0.90053834]]

  [[0.61906398 0.68988898]
   [0.75189445 0.47143527]
   [0.08093368 0.73620037]]

  [[0.35522778 0.41108182]
   [0.09718835 0.83747834]
   [0.94859089 0.5614391 ]]]


In [61]:
print(c[0, 1, 1, 0])

0.8377361160854807


In [40]:

print(c[0, 1, 2, 1])


0.4044876258074952


In [67]:
A

array([[1, 2],
       [3, 4]])

In [68]:
B

array([[5, 6],
       [7, 8]])

In [69]:
np.multiply(A,B)

array([[ 5, 12],
       [21, 32]])

In [71]:
A.dot(B)

array([[19, 22],
       [43, 50]])

In [39]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    print(x)
    for y in x:
        print(y)

[1 2 3]
1
2
3
[4 5 6]
4
5
6


In [41]:
arr = np.array(['WEb', 'DA', 'UX'])

print(np.sort(arr))
arr

['DA' 'UX' 'WEb']


array(['WEb', 'DA', 'UX'], dtype='<U3')

In [41]:
(lambda x: x*2)(12)

24

In [72]:
list_1 = [1,2,3,4,5,6,7,8,9]
list_1


[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [75]:
w=filter(lambda x: x%2==0, list_1)
w

In [77]:
list(filter(lambda x: x%2==0, list_1))

[2, 4, 6, 8]

In [84]:
f=np.empty((2,2))
f
@ A.dot(B)
*

array([[ 1.02888091e+189, -2.93236711e-256],
       [ 1.19723338e+044, -1.67015314e+081]])

In [ ]:
Map(). This is another inbuilt python library with the syntax map(function, iterable).
This returns a modified list where every value in the original list has been changed based on a function. The example below cubes every number in the list.
list_1 = [1,2,3,4,5,6,7,8,9]
cubed = map(lambda x: pow(x,3), list_1)
list(cubed)
###Results
[1, 8, 27, 64, 125, 216, 343, 512, 729]

In [ ]:
# y : 3
# z : 5
for x in c:
    for y in x:
        for z in y:
            print (z)
            if z>d_min and z<d_mean:
                f[x][y][z]=z+25
            elif z>d_mean and z<d_max:
                f[x][y][z]=z+75
            elif z == d_mean:
                f[x][y][z]=z+50
            elif z == d_min:
                f[x][y][z] == 0
            elif z == d_max:
                f[x][y][z]==100
            else: f[x][y][z]=0
f